# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroUsuario(object):
    def setupUi(self, CadastroUsuario):
        CadastroUsuario.setObjectName("CadastroUsuario")
        CadastroUsuario.resize(538, 300)
        self.pbSalvarEditar = QtWidgets.QPushButton(CadastroUsuario)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(68, 229, 81, 31))
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")
        self.pbApagar = QtWidgets.QPushButton(CadastroUsuario)
        self.pbApagar.setGeometry(QtCore.QRect(358, 229, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pbApagar.setFont(font)
        self.pbApagar.setObjectName("pbApagar")
        self.leLogin = QtWidgets.QLineEdit(CadastroUsuario)
        self.leLogin.setGeometry(QtCore.QRect(30, 120, 500, 20))
        self.leLogin.setObjectName("leLogin")
        self.label_2 = QtWidgets.QLabel(CadastroUsuario)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.leSenha = QtWidgets.QLineEdit(CadastroUsuario)
        self.leSenha.setGeometry(QtCore.QRect(30, 180, 500, 20))
        self.leSenha.setObjectName("leSenha")
        self.label_4 = QtWidgets.QLabel(CadastroUsuario)
        self.label_4.setGeometry(QtCore.QRect(32, 161, 61, 10))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(CadastroUsuario)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 61, 16))
        self.label_3.setObjectName("label_3")
        self.leNome = QtWidgets.QLineEdit(CadastroUsuario)
        self.leNome.setGeometry(QtCore.QRect(30, 60, 500, 20))
        self.leNome.setObjectName("leNome")

        self.retranslateUi(CadastroUsuario)
        QtCore.QMetaObject.connectSlotsByName(CadastroUsuario)

    def retranslateUi(self, CadastroUsuario):
        _translate = QtCore.QCoreApplication.translate
        CadastroUsuario.setWindowTitle(_translate("CadastroUsuario", "Dialog"))
        self.pbSalvarEditar.setText(_translate("CadastroUsuario", "Salvar"))
        self.pbApagar.setText(_translate("CadastroUsuario", "Apagar"))
        self.label_2.setText(_translate("CadastroUsuario", "E-mail"))
        self.label_4.setText(_translate("CadastroUsuario", "Senha"))
        self.label_3.setText(_translate("CadastroUsuario", "Nome"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastroUsuario = QtWidgets.QDialog()
    ui = Ui_CadastroUsuario()
    ui.setupUi(CadastroUsuario)
    CadastroUsuario.show()
    sys.exit(app.exec_())
