# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indice_desvalorizacao_monetaria.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndiceDesvalorizacaoMonetaria(object):
    def setupUi(self, IndiceDesvalorizacaoMonetaria):
        IndiceDesvalorizacaoMonetaria.setObjectName("IndiceDesvalorizacaoMonetaria")
        IndiceDesvalorizacaoMonetaria.resize(587, 369)
        self.pbSalvarEditar = QtWidgets.QPushButton(IndiceDesvalorizacaoMonetaria)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(70, 310, 81, 31))
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")
        self.pbApagar = QtWidgets.QPushButton(IndiceDesvalorizacaoMonetaria)
        self.pbApagar.setGeometry(QtCore.QRect(360, 310, 81, 31))
        self.pbApagar.setObjectName("pbApagar")
        self.label_2 = QtWidgets.QLabel(IndiceDesvalorizacaoMonetaria)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(IndiceDesvalorizacaoMonetaria)
        self.label.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label.setObjectName("label")
        self.leIndice = QtWidgets.QLineEdit(IndiceDesvalorizacaoMonetaria)
        self.leIndice.setGeometry(QtCore.QRect(20, 80, 500, 20))
        self.leIndice.setObjectName("leIndice")
        self.pteDescricao = QtWidgets.QPlainTextEdit(IndiceDesvalorizacaoMonetaria)
        self.pteDescricao.setGeometry(QtCore.QRect(20, 160, 541, 71))
        self.pteDescricao.setObjectName("pteDescricao")

        self.retranslateUi(IndiceDesvalorizacaoMonetaria)
        QtCore.QMetaObject.connectSlotsByName(IndiceDesvalorizacaoMonetaria)

    def retranslateUi(self, IndiceDesvalorizacaoMonetaria):
        _translate = QtCore.QCoreApplication.translate
        IndiceDesvalorizacaoMonetaria.setWindowTitle(_translate("IndiceDesvalorizacaoMonetaria", "Dialog"))
        self.pbSalvarEditar.setText(_translate("IndiceDesvalorizacaoMonetaria", "Salvar"))
        self.pbApagar.setText(_translate("IndiceDesvalorizacaoMonetaria", "Apagar"))
        self.label_2.setText(_translate("IndiceDesvalorizacaoMonetaria", "Descrição"))
        self.label.setText(_translate("IndiceDesvalorizacaoMonetaria", "Indice"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndiceDesvalorizacaoMonetaria = QtWidgets.QDialog()
    ui = Ui_IndiceDesvalorizacaoMonetaria()
    ui.setupUi(IndiceDesvalorizacaoMonetaria)
    IndiceDesvalorizacaoMonetaria.show()
    sys.exit(app.exec_())
