# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fornecedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fornecedor(object):
    def setupUi(self, Fornecedor):
        Fornecedor.setObjectName("Fornecedor")
        Fornecedor.resize(586, 370)
        self.pbApagar = QtWidgets.QPushButton(Fornecedor)
        self.pbApagar.setGeometry(QtCore.QRect(390, 260, 81, 31))
        self.pbApagar.setObjectName("pbApagar")
        self.leFornecedor = QtWidgets.QLineEdit(Fornecedor)
        self.leFornecedor.setGeometry(QtCore.QRect(20, 50, 500, 20))
        self.leFornecedor.setObjectName("leFornecedor")
        self.pbSalvarEditar = QtWidgets.QPushButton(Fornecedor)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(100, 260, 81, 31))
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")
        self.cbinstituicaoBancaria = QtWidgets.QCheckBox(Fornecedor)
        self.cbinstituicaoBancaria.setGeometry(QtCore.QRect(20, 100, 121, 17))
        self.cbinstituicaoBancaria.setObjectName("cbinstituicaoBancaria")
        self.pteDescricao = QtWidgets.QPlainTextEdit(Fornecedor)
        self.pteDescricao.setGeometry(QtCore.QRect(20, 140, 541, 91))
        self.pteDescricao.setObjectName("pteDescricao")

        self.retranslateUi(Fornecedor)
        QtCore.QMetaObject.connectSlotsByName(Fornecedor)

    def retranslateUi(self, Fornecedor):
        _translate = QtCore.QCoreApplication.translate
        Fornecedor.setWindowTitle(_translate("Fornecedor", "Dialog"))
        self.pbApagar.setText(_translate("Fornecedor", "Apagar"))
        self.pbSalvarEditar.setText(_translate("Fornecedor", "Salvar"))
        self.cbinstituicaoBancaria.setText(_translate("Fornecedor", "InstituiçãoBancária"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fornecedor = QtWidgets.QDialog()
    ui = Ui_Fornecedor()
    ui.setupUi(Fornecedor)
    Fornecedor.show()
    sys.exit(app.exec_())
