# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tipo_investimento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipoInvestimento(object):
    def setupUi(self, TipoInvestimento):
        TipoInvestimento.setObjectName("TipoInvestimento")
        TipoInvestimento.resize(591, 368)
        self.label = QtWidgets.QLabel(TipoInvestimento)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TipoInvestimento)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_2.setObjectName("label_2")
        self.pteDescricao = QtWidgets.QPlainTextEdit(TipoInvestimento)
        self.pteDescricao.setGeometry(QtCore.QRect(20, 140, 541, 71))
        self.pteDescricao.setObjectName("pteDescricao")
        self.leTipoInvestimento = QtWidgets.QLineEdit(TipoInvestimento)
        self.leTipoInvestimento.setGeometry(QtCore.QRect(20, 60, 500, 20))
        self.leTipoInvestimento.setObjectName("leTipoInvestimento")
        self.pbSalvarEditar = QtWidgets.QPushButton(TipoInvestimento)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(70, 290, 81, 31))
        self.pbSalvarEditar.setStyleSheet("#pbSalvarEditar{\n"
"    border_radius: 10px;\n"
"}")
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")
        self.pbApagar = QtWidgets.QPushButton(TipoInvestimento)
        self.pbApagar.setGeometry(QtCore.QRect(360, 290, 81, 31))
        self.pbApagar.setObjectName("pbApagar")

        self.retranslateUi(TipoInvestimento)
        QtCore.QMetaObject.connectSlotsByName(TipoInvestimento)

    def retranslateUi(self, TipoInvestimento):
        _translate = QtCore.QCoreApplication.translate
        TipoInvestimento.setWindowTitle(_translate("TipoInvestimento", "Dialog"))
        self.label.setText(_translate("TipoInvestimento", "Investimento"))
        self.label_2.setText(_translate("TipoInvestimento", "Descrição"))
        self.pbSalvarEditar.setText(_translate("TipoInvestimento", "Salvar"))
        self.pbApagar.setText(_translate("TipoInvestimento", "Apagar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TipoInvestimento = QtWidgets.QDialog()
    ui = Ui_TipoInvestimento()
    ui.setupUi(TipoInvestimento)
    TipoInvestimento.show()
    sys.exit(app.exec_())
