# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'produto_investimento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProdutoInvestimento(object):
    def setupUi(self, ProdutoInvestimento):
        ProdutoInvestimento.setObjectName("ProdutoInvestimento")
        ProdutoInvestimento.resize(587, 461)
        self.label = QtWidgets.QLabel(ProdutoInvestimento)
        self.label.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ProdutoInvestimento)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.pteDescricao = QtWidgets.QPlainTextEdit(ProdutoInvestimento)
        self.pteDescricao.setGeometry(QtCore.QRect(30, 130, 511, 87))
        self.pteDescricao.setObjectName("pteDescricao")
        self.leTipoInvestimento = QtWidgets.QLineEdit(ProdutoInvestimento)
        self.leTipoInvestimento.setGeometry(QtCore.QRect(30, 60, 500, 20))
        self.leTipoInvestimento.setObjectName("leTipoInvestimento")
        self.pbSalvarEditar = QtWidgets.QPushButton(ProdutoInvestimento)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(70, 390, 81, 31))
        self.pbSalvarEditar.setStyleSheet("#pbSalvarEditar{\n"
"    border_radius: 10px;\n"
"}")
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")
        self.pbApagar = QtWidgets.QPushButton(ProdutoInvestimento)
        self.pbApagar.setGeometry(QtCore.QRect(360, 390, 81, 31))
        self.pbApagar.setObjectName("pbApagar")
        self.tbwProdutoInvestimento = QtWidgets.QTableWidget(ProdutoInvestimento)
        self.tbwProdutoInvestimento.setGeometry(QtCore.QRect(30, 230, 511, 121))
        self.tbwProdutoInvestimento.setObjectName("tbwProdutoInvestimento")
        self.tbwProdutoInvestimento.setColumnCount(0)
        self.tbwProdutoInvestimento.setRowCount(0)

        self.retranslateUi(ProdutoInvestimento)
        QtCore.QMetaObject.connectSlotsByName(ProdutoInvestimento)

    def retranslateUi(self, ProdutoInvestimento):
        _translate = QtCore.QCoreApplication.translate
        ProdutoInvestimento.setWindowTitle(_translate("ProdutoInvestimento", "Dialog"))
        self.label.setText(_translate("ProdutoInvestimento", "Investimento"))
        self.label_2.setText(_translate("ProdutoInvestimento", "Descrição"))
        self.pbSalvarEditar.setText(_translate("ProdutoInvestimento", "Salvar"))
        self.pbApagar.setText(_translate("ProdutoInvestimento", "Apagar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProdutoInvestimento = QtWidgets.QDialog()
    ui = Ui_ProdutoInvestimento()
    ui.setupUi(ProdutoInvestimento)
    ProdutoInvestimento.show()
    sys.exit(app.exec_())
