# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valor_desvalorizacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ValorDesvalorizacao(object):
    def setupUi(self, ValorDesvalorizacao):
        ValorDesvalorizacao.setObjectName("ValorDesvalorizacao")
        ValorDesvalorizacao.resize(587, 441)
        self.label = QtWidgets.QLabel(ValorDesvalorizacao)
        self.label.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(ValorDesvalorizacao)
        self.label_3.setGeometry(QtCore.QRect(270, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(ValorDesvalorizacao)
        self.textEdit.setGeometry(QtCore.QRect(20, 230, 541, 71))
        self.textEdit.setObjectName("textEdit")
        self.pbApagar = QtWidgets.QPushButton(ValorDesvalorizacao)
        self.pbApagar.setGeometry(QtCore.QRect(410, 360, 75, 23))
        self.pbApagar.setObjectName("pbApagar")
        self.comboBox = QtWidgets.QComboBox(ValorDesvalorizacao)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(ValorDesvalorizacao)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(ValorDesvalorizacao)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(ValorDesvalorizacao)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 149, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(ValorDesvalorizacao)
        self.lineEdit.setGeometry(QtCore.QRect(20, 150, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pbSalvarEditar = QtWidgets.QPushButton(ValorDesvalorizacao)
        self.pbSalvarEditar.setGeometry(QtCore.QRect(30, 360, 75, 23))
        self.pbSalvarEditar.setObjectName("pbSalvarEditar")

        self.retranslateUi(ValorDesvalorizacao)
        QtCore.QMetaObject.connectSlotsByName(ValorDesvalorizacao)

    def retranslateUi(self, ValorDesvalorizacao):
        _translate = QtCore.QCoreApplication.translate
        ValorDesvalorizacao.setWindowTitle(_translate("ValorDesvalorizacao", "Dialog"))
        self.label.setText(_translate("ValorDesvalorizacao", "Indice"))
        self.label_3.setText(_translate("ValorDesvalorizacao", "Mês/Ano"))
        self.pbApagar.setText(_translate("ValorDesvalorizacao", "Apagar"))
        self.label_4.setText(_translate("ValorDesvalorizacao", "Observação"))
        self.label_2.setText(_translate("ValorDesvalorizacao", "Valor"))
        self.pbSalvarEditar.setText(_translate("ValorDesvalorizacao", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ValorDesvalorizacao = QtWidgets.QDialog()
    ui = Ui_ValorDesvalorizacao()
    ui.setupUi(ValorDesvalorizacao)
    ValorDesvalorizacao.show()
    sys.exit(app.exec_())
